# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

router = DefaultRouter()
# register the ViewSet per your instruction
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # keep the existing ListAPIView route
    path('books/', BookList.as_view(), name='book-list'),

    # include all routes generated by the router (CRUD)
    path('', include(router.urls)),
]

